# Uncomment this line to define a global platform for your project
# platform :ios, "8.0"

target "Pear" do

pod 'Facebook-iOS-SDK', '~> 3.23'
pod 'Parse', '~> 1.6'
pod 'ParseFacebookUtils', '~> 1.6'

end

target "PearTests" do

end

