# Uncomment this line to define a global platform for your project
# platform :ios, "8.0"

target "Pear" do

pod 'Facebook-iOS-SDK', '~> 4.0'
pod 'Parse', '~> 1.7'
pod 'ParseFacebookUtilsV4', '~> 1.7'

end

target "PearTests" do

end

